# Generated by Django 3.1.7 on 2021-03-30 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languages',
            old_name='title',
            new_name='pr_languages',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pr_languages',
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price_per_month', models.IntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('pr_languages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.languages')),
            ],
        ),
    ]
