# Generated by Django 3.1.7 on 2021-03-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210330_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languages',
            old_name='pr_languages',
            new_name='title',
        ),
    ]
